# ML lab 04-1: multi-variable linear regression
---

#### Hypothesis using matrix

x1 | x2 | x3 | Y 
-- | -- | -- | --
73 | 80 | 75 | 152
93 | 88 | 93 | 185
89 | 91 | 90 | 180
96 | 98 | 100 | 196
73 | 66 | 70 | 142

> x : 연습 시험 점수  
> y : 기말 시험 점수  
> 연습 시험 점수만으로 기말 시험 점수를 예측

$$H(x1, x2, x3) = x1w1 + x2w2 + x3w3 + b $$

In [2]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholder for a tensor that will be always fed
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-6)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        

0 Cost:  3113.8 
Prediction:
 [ 196.83612061  246.99931335  238.13221741  257.4624939   192.57495117]
10 Cost:  1272.9 
Prediction:
 [ 178.92683411  225.47122192  216.92147827  234.36447144  176.15391541]
20 Cost:  524.614 
Prediction:
 [ 167.50917053  211.74557495  203.39866638  219.63833618  165.6842041 ]
30 Cost:  220.452 
Prediction:
 [ 160.23025513  202.9944458   194.77728271  210.24975586  159.00875854]
40 Cost:  96.8131 
Prediction:
 [ 155.5900116   197.4147644   189.28079224  204.26411438  154.75234985]
50 Cost:  46.5543 
Prediction:
 [ 152.63212585  193.85716248  185.77668762  200.44813538  152.03825378]
60 Cost:  26.1212 
Prediction:
 [ 150.74673462  191.58860779  183.54272461  198.01530457  150.30741882]
70 Cost:  17.8121 
Prediction:
 [ 149.54516602  190.14198303  182.11859131  196.46434021  149.20347595]
80 Cost:  14.431 
Prediction:
 [ 148.77957153  189.21934509  181.21078491  195.47567749  148.4992218 ]
90 Cost:  13.053 
Prediction:
 [ 148.29193115  188.63079834  180.632

820 Cost:  11.6728 
Prediction:
 [ 147.52531433  187.53297424  179.64196777  193.75964355  147.17474365]
830 Cost:  11.6669 
Prediction:
 [ 147.52656555  187.53208923  179.64234924  193.75994873  147.17355347]
840 Cost:  11.661 
Prediction:
 [ 147.52781677  187.53121948  179.6427002   193.76025391  147.17236328]
850 Cost:  11.6551 
Prediction:
 [ 147.52906799  187.53031921  179.64308167  193.76055908  147.1711731 ]
860 Cost:  11.6492 
Prediction:
 [ 147.53034973  187.52944946  179.64346313  193.76086426  147.17001343]
870 Cost:  11.6432 
Prediction:
 [ 147.53160095  187.52857971  179.6438446   193.76116943  147.16880798]
880 Cost:  11.6373 
Prediction:
 [ 147.53285217  187.52767944  179.64419556  193.76148987  147.16764832]
890 Cost:  11.6314 
Prediction:
 [ 147.53408813  187.52679443  179.64456177  193.76176453  147.16644287]
900 Cost:  11.6256 
Prediction:
 [ 147.53535461  187.52592468  179.64494324  193.76205444  147.16526794]
910 Cost:  11.6196 
Prediction:
 [ 147.53660583  187.525

1730 Cost:  11.1472 
Prediction:
 [ 147.63902283  187.45462036  179.67634583  193.78799438  147.06900024]
1740 Cost:  11.1415 
Prediction:
 [ 147.64025879  187.45376587  179.67671204  193.78829956  147.06784058]
1750 Cost:  11.1359 
Prediction:
 [ 147.64149475  187.45291138  179.67707825  193.78858948  147.06669617]
1760 Cost:  11.1302 
Prediction:
 [ 147.64271545  187.45205688  179.67744446  193.78889465  147.0655365 ]
1770 Cost:  11.1246 
Prediction:
 [ 147.64393616  187.45118713  179.67781067  193.78919983  147.06439209]
1780 Cost:  11.119 
Prediction:
 [ 147.6451416   187.45030212  179.67814636  193.78947449  147.0632019 ]
1790 Cost:  11.1134 
Prediction:
 [ 147.64637756  187.44946289  179.67852783  193.7897644   147.0620575 ]
1800 Cost:  11.1077 
Prediction:
 [ 147.64761353  187.44859314  179.67887878  193.79006958  147.06091309]
1810 Cost:  11.1022 
Prediction:
 [ 147.64881897  187.44773865  179.679245    193.79037476  147.05976868]
1820 Cost:  11.0965 
Prediction:
 [ 147.6500549

#### Matrix

여러개의 변수, 여러 셋의 데이터를 한번에 입력할 수 있음

$$\begin{pmatrix} x1 & x2 & x3 \end{pmatrix}\cdot\begin{pmatrix} w1\\ w2\\ w3 \end{pmatrix} = (x1w1 + x2w2 + x3w3)$$

$$H(X) = XW$$

In [5]:
import tensorflow as tf
x_data = [[73., 80., 75.],  
          [93., 88., 93.], 
          [89., 91., 90.], 
          [96., 98., 100.], 
          [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholder for a tensor that will be always fed
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-6)
train = optimizer.minimize(cost)

# Launch the graph in a session
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        

0 Cost:  46629.4 
Prediction:
 [[-47.56793976]
 [-40.30652618]
 [-48.2428093 ]
 [-53.54328918]
 [-25.89897919]]
10 Cost:  18972.2 
Prediction:
 [[ 21.85651588]
 [ 43.1324234 ]
 [ 33.97313309]
 [ 35.98760223]
 [ 37.74310303]]
20 Cost:  7730.23 
Prediction:
 [[ 66.11915588]
 [ 96.32875061]
 [ 86.39047241]
 [ 93.068573  ]
 [ 78.31767273]]
30 Cost:  3160.65 
Prediction:
 [[  94.33972168]
 [ 130.24372864]
 [ 119.80958557]
 [ 129.46092224]
 [ 104.18540955]]
40 Cost:  1303.22 
Prediction:
 [[ 112.33263397]
 [ 151.86578369]
 [ 141.11628723]
 [ 152.66317749]
 [ 120.6767807 ]]
50 Cost:  548.206 
Prediction:
 [[ 123.80487061]
 [ 165.65049744]
 [ 154.70072937]
 [ 167.45605469]
 [ 131.19021606]]
60 Cost:  241.304 
Prediction:
 [[ 131.11981201]
 [ 174.43847656]
 [ 163.36177063]
 [ 176.88748169]
 [ 137.89241028]]
70 Cost:  116.546 
Prediction:
 [[ 135.78425598]
 [ 180.04072571]
 [ 168.88386536]
 [ 182.90072632]
 [ 142.16468811]]
80 Cost:  65.8258 
Prediction:
 [[ 138.7588501 ]
 [ 183.61192322]
 [ 172

780 Cost:  29.9593 
Prediction:
 [[ 144.1360321 ]
 [ 189.79411316]
 [ 178.64205933]
 [ 193.51208496]
 [ 149.54566956]]
790 Cost:  29.9432 
Prediction:
 [[ 144.13813782]
 [ 189.79264832]
 [ 178.64268494]
 [ 193.51255798]
 [ 149.54374695]]
800 Cost:  29.9272 
Prediction:
 [[ 144.14025879]
 [ 189.79121399]
 [ 178.64335632]
 [ 193.51304626]
 [ 149.5418396 ]]
810 Cost:  29.9113 
Prediction:
 [[ 144.1423645 ]
 [ 189.78979492]
 [ 178.64401245]
 [ 193.51358032]
 [ 149.53994751]]
820 Cost:  29.8953 
Prediction:
 [[ 144.14451599]
 [ 189.78839111]
 [ 178.64471436]
 [ 193.51409912]
 [ 149.53807068]]
830 Cost:  29.8793 
Prediction:
 [[ 144.14665222]
 [ 189.7869873 ]
 [ 178.64538574]
 [ 193.51463318]
 [ 149.53617859]]
840 Cost:  29.8634 
Prediction:
 [[ 144.14877319]
 [ 189.78559875]
 [ 178.64605713]
 [ 193.51516724]
 [ 149.53430176]]
850 Cost:  29.8474 
Prediction:
 [[ 144.15090942]
 [ 189.78421021]
 [ 178.64674377]
 [ 193.51571655]
 [ 149.53240967]]
860 Cost:  29.8315 
Prediction:
 [[ 144.1530304 

1670 Cost:  28.569 
Prediction:
 [[ 144.3212738 ]
 [ 189.66749573]
 [ 178.69882202]
 [ 193.55541992]
 [ 149.37750244]]
1680 Cost:  28.5538 
Prediction:
 [[ 144.32330322]
 [ 189.6660614 ]
 [ 178.69941711]
 [ 193.55584717]
 [ 149.37562561]]
1690 Cost:  28.5385 
Prediction:
 [[ 144.3253479 ]
 [ 189.66462708]
 [ 178.70002747]
 [ 193.55632019]
 [ 149.37373352]]
1700 Cost:  28.5234 
Prediction:
 [[ 144.32737732]
 [ 189.66320801]
 [ 178.70063782]
 [ 193.5567627 ]
 [ 149.37187195]]
1710 Cost:  28.5081 
Prediction:
 [[ 144.32940674]
 [ 189.66177368]
 [ 178.70124817]
 [ 193.55722046]
 [ 149.36997986]]
1720 Cost:  28.4929 
Prediction:
 [[ 144.33145142]
 [ 189.66036987]
 [ 178.70185852]
 [ 193.55767822]
 [ 149.36810303]]
1730 Cost:  28.4776 
Prediction:
 [[ 144.33351135]
 [ 189.65893555]
 [ 178.70246887]
 [ 193.5581665 ]
 [ 149.3662262 ]]
1740 Cost:  28.4625 
Prediction:
 [[ 144.33552551]
 [ 189.65750122]
 [ 178.70307922]
 [ 193.55859375]
 [ 149.36434937]]
1750 Cost:  28.4474 
Prediction:
 [[ 144.